# Generated by Django 5.2.3 on 2025-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinTF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.SlugField(max_length=20)),
                ('satellite', models.CharField(max_length=20)),
                ('validation_grade', models.CharField(max_length=5)),
                ('prediction_method', models.CharField(max_length=100)),
                ('microscopy_result', models.CharField(max_length=200)),
                ('motif_enrichment', models.DecimalField(decimal_places=5, max_digits=10)),
                ('motif_q_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('existing_images', models.CharField(max_length=100)),
                ('existing_images_link', models.CharField(max_length=200)),
            ],
        ),
    ]
