# Generated by Django 5.2.3 on 2025-06-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_proteintf_af3_proteintf_ensembl_proteintf_pdb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteintf',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
